const modules=[
 ['Office Operations','Coordinate the day-to-day operation from one connected workspace.','OO'],
 ['Projects & Jobs','Keep live jobs, progress, site information and project records connected.','PJ'],
 ['Project Map','See active and scheduled jobs geographically, colour-coded by customer.','MP'],
 ['Weekly Planner','Plan projects across the week with crews, vehicles and live project links.','WP'],
 ['Staff & Employees','Attendance, pay, qualifications, employment and workforce records.','SE'],
 ['Staff Manager','A focused management workspace for staff records, attendance and workforce control.','SM'],
 ['Staff Portal','Put live job information and site tools in the hands of the workforce on mobile.','SP'],
 ['Customers','Keep customer contacts, addresses, project history and relationships together.','CU'],
 ['Client Portal','Give clients controlled self-service access to their own projects and updates.','CP'],
 ['Major Accounts','Manage strategic prospects, personalised introductions and conversion to customers.','MA'],
 ['Purchasing Ledger','Supplier accounts, purchase invoices, payments and goods received in one place.','PL'],
 ['Scaffold Stock','See owned stock, estimated material on live sites and approximate availability.','ST'],
 ['Fleet & Vehicles','Vehicle records, MOT, tax, insurance, servicing and operational status.','FV'],
 ['Plant & Equipment','Plant, tools and equipment records, inspections, maintenance and assignments.','PE'],
 ['Plant Manager','A focused workspace for plant and equipment control without wider system access.','PM'],
 ['Accounts & Finance','Invoices, payments, money owed and the company financial position.','AF'],
 ['Compliance & Safety','Inspections, handovers, safety records and compliance actions.','HS'],
 ['Office Staff Member','A restricted workspace for everyday office administration.','OS'],
 ['Remote Sales','A restricted workspace for prospects, introductions and sales follow-up.','RS'],
 ['AI Briefing','Ask about the operation and surface the matters that need attention.','AI'],
 ['Subscription Details','See the planned JonCor subscription and what the connected platform includes.','£']
];
const demoData={
 Management:['4 active projects','2 operational matters','1 client message'],
 Projects:['Riverside Apartments — Chelmsford','ABC Constructions','Status: Active'],
 'Staff Portal':['Today: Riverside Apartments','Site notes & photo updates','Scaffold inspection evidence'],
 'Client Portal':['Project visibility','Inspection records','Site photos, documents & messages'],
 'Fleet & Plant':['Vehicles & plant register','Maintenance visibility','Fuel & compliance'],
 Commercial:['Quotation control','Project commercial information','Costs & variations'],
 Compliance:['Scaffold & safety inspections','PPE / harness / equipment records','Expiry & action awareness'],
 'Office Workspace':['Role-based office access','Customers & projects','Controlled permissions'],
 'Remote Sales':['Prospect workspace','Introduction outreach','Restricted sales access'],
 'Prospect Outreach':['Prospect discovery','Mail-shot campaigns','Outbound email workflow'],
 'AI Briefing':['Vehicle inspection approaching','Client message awaiting response','Project compliance item requires review'],
 'Subscription Details':['£149 + VAT per month','14-day free trial · no card required','Complete connected operational platform']
};
let screen='landing',active='Office Operations',tour=false,step=0,projectTab='Overview';
const tourOrder=['Office Operations','Projects & Jobs','Project Map','Weekly Planner','Staff Manager','Staff Portal','Client Portal','Major Accounts','Purchasing Ledger','Scaffold Stock','Plant Manager','AI Briefing','Subscription Details'];
function esc(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;')}
function officeFacsimile(mode){const mobile=mode==='mobile';return `<div class="facUI ${mobile?'facMobileUI':''}"><div class="facTop"><span>“Operational intelligence should make the next decision clearer.”</span><div><b>← Back</b><b>⌂ Home</b><b class="facLogout">↪ Log out</b></div></div><div class="facBanner"><img src="assets/joncor-jc-logo.png"><div><strong>JonCor AI <em>V4</em></strong><small>OPERATIONAL INTELLIGENCE PLATFORM</small><b>Smarter Construction Through Intelligence</b></div><span></span></div><div class="facContent"><section class="facOffice"><h2>📁 Office Operations</h2><p>A simple action monitor for unfinished administration, payments and staff availability.</p></section><div class="facPortalRow"><div><i>🔐</i><b>CLIENT PORTAL</b><small>Open and monitor the client-facing portal.</small><em>›</em></div><div><i>📱</i><b>STAFF PORTAL</b><small>Open and monitor the staff-facing portal.</small><em>›</em></div></div><button class="facBrief">✦ <b>BRIEFING</b><span>Talk to JonCor</span> ›</button>${mobile?'<div class="facMessage"><b>✉ Client Messages</b><small>No unread client messages</small></div><div class="facAttention"><small>OFFICE MANAGER · ACTION MONITOR</small><b>What needs attention</b></div>':''}</div></div>`}
function render(){const a=document.querySelector('#app'); if(screen==='landing'){a.innerHTML=`
<header class="top"><div class="brand"><span class="mark logoMark"><img src="assets/joncor-jc-logo.png" alt="JonCor JC logo"></span><b>JonCor AI V4</b><small>OPERATIONAL INTELLIGENCE</small></div><button class="contact subscriptionTop" onclick="subscription()">Register Subscription Interest</button></header>
<main class="hero"><section><div class="eyebrow">BUILT AROUND REAL OPERATIONS</div><h1>Your business.<br><span>Connected. Controlled. Intelligent.</span></h1><p class="lead">Bring staff, projects, customers, fleet, commercial operations, compliance and documents together — with intelligence that helps show what needs attention.</p><div class="actions"><button class="primary" onclick="enter(true)">Explore the interactive demo →</button><button class="ghost" onclick="enter(false)">Explore freely</button></div><div class="trust"><span>✓ Desktop</span><span>✓ Mobile</span><span>✓ Staff Portal</span><span>✓ Client Portal</span><span>✓ AI Briefing</span></div></section><section class="device facsimileDevice"><div class="glow"></div><div class="facLaptop"><div class="facScreen">${officeFacsimile('desktop')}</div><div class="facBase"></div></div><div class="facPhone"><div class="facNotch"></div>${officeFacsimile('mobile')}</div></section></main>
<section class="why"><p>WHY JONCOR?</p><h2>Replace disconnected paperwork, spreadsheets and messages with one connected operational picture.</h2><div class="whyIntro">JonCor brings the people running the office, the teams working on site and the customers waiting for information into one controlled environment. Instead of the same job being managed through separate calls, messages, photographs and spreadsheets, the operational record can move with the work.</div><div class="benefits"><div><b>ONE CONNECTED OPERATION</b><span>Projects, workforce, customers, fleet, commercial activity, compliance and documents can sit around the same live operational record.</span></div><div><b>LESS REPEATED ADMIN</b><span>Information captured at the point of work can feed the wider operation, reducing the need to re-key, chase and redistribute routine updates.</span></div><div><b>BETTER MANAGEMENT VISIBILITY</b><span>See live activity, approaching actions and client communication in context, so attention can be directed where it is actually needed.</span></div></div><div class="sellingStrip"><span>OFFICE</span><i>→</i><span>STAFF PORTAL</span><i>→</i><span>LIVE PROJECT RECORD</span><i>→</i><span>CLIENT PORTAL</span><i>→</i><span>INTELLIGENCE</span></div></section>`}else{renderDemo(a)} }
function renderDemo(a){const mobile=active==='Staff Portal';const client=active==='Client Portal';a.innerHTML=`<div class="demoShell"><aside><div class="brand compact"><span class="mark logoMark"><img src="assets/joncor-jc-logo.png" alt="JonCor JC logo"></span><b>JonCor AI V4</b><small>INTERACTIVE DEMO</small></div><nav>${modules.map(m=>`<button class="${active===m[0]?'on':''}" onclick="openMod('${m[0]}')"><i>${m[2]}</i><span>${m[0]}</span></button>`).join('')}</nav></aside><main class="workspace"><div class="appHeader"><div class="appQuote">“Operational intelligence should make the next decision clearer.”</div><div class="appBanner"><img src="assets/joncor-jc-logo.png" alt="JonCor logo"><div><b>JonCor AI <span>V4</span></b><small>OPERATIONAL INTELLIGENCE PLATFORM</small><strong>Smarter Construction Through Intelligence</strong></div></div></div><div class="demoTop"><div><small>DEMONSTRATION ENVIRONMENT</small><h2>${active}</h2></div><div class="topActions"><button onclick="startTour()">Guided tour</button><button onclick="subscription()">Subscription Interest</button></div></div>${tour?guide():''}<section class="workspaceHero"><div><span class="live">● DEMO DATA</span><h1>${active}</h1><p>${modules.find(m=>m[0]===active)[1]}</p></div><div class="metric">${active==='AI Briefing'?'3':'LIVE'}<small>${active==='AI Briefing'?'matters requiring attention':'connected demonstration'}</small></div></section>${mobile?phoneDemo():client?clientDemo():standardDemo()}<section class="conversion"><div><small>LIKE WHAT YOU'RE SEEING?</small><h2>Imagine JonCor configured around your business.</h2><p>Explore JonCor at your own pace, then register your interest in a JonCor AI V4 subscription.</p></div><div><button class="primary" onclick="subscription()">Register Subscription Interest</button></div></section></main></div>`}
function standardDemo(){
 const cards=(items)=>`<div class="newGrid">${items.map(x=>`<button onclick="detail('${x[2].replaceAll("'","&#39;")}')"><i>${x[0]}</i><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</div>`;
 const content={
 'Office Operations':`<div class="opsBoard"><div class="opsKpis"><div><small>ACTIVE PROJECTS</small><b>2</b><span>Live project records</span></div><div><small>STAFF IN TODAY</small><b>7</b><span>Attendance connected</span></div><div><small>FLEET IN SERVICE</small><b>0</b><span>Live fleet position</span></div><div><small>COMPLIANCE ISSUES</small><b>0</b><span>Current records</span></div></div><div class="activity"><h3>Office Operations control</h3><button onclick="openMod('Project Map')"><b>Project Map</b><span>See live jobs geographically</span><em>OPEN MAP →</em></button><button onclick="openMod('Weekly Planner')"><b>Weekly Planner</b><span>Projects, crews and vehicles</span><em>OPEN PLANNER →</em></button><button onclick="openMod('Purchasing Ledger')"><b>Purchasing Ledger</b><span>Supplier accounts and liabilities</span><em>OPEN LEDGER →</em></button><button onclick="openMod('AI Briefing')"><b>Briefing</b><span>Ask JonCor about the operation</span><em>ASK JONCOR →</em></button></div></div>`,
 'Projects & Jobs':projectDemo(),
 'Project Map':`<div class="mapDemo"><div class="mapCanvas"><div class="mapRoad r1"></div><div class="mapRoad r2"></div><div class="mapRoad r3"></div><span class="mapLabel l1">CHELMSFORD</span><span class="mapLabel l2">LONDON</span><button class="pin pinA" onclick="detail('Riverside Apartments · ABC Constructions · Chelmsford · Active project')">A</button><button class="pin pinB" onclick="detail('A second live project would appear here using its project site address.')">B</button></div><div class="mapLegend"><small>CUSTOMER COLOUR KEY</small><h3>Projects by location</h3><p><i class="dot cyan"></i><b>ABC Constructions</b></p><p><i class="dot violet"></i><b>Example Customer</b></p><div class="whyPanel"><small>CONNECTED TO PROJECTS</small><p>Project site addresses create the geographical view. Customer colours are assigned automatically so the office can see who is where at a glance.</p></div></div></div>`,
 'Weekly Planner':`<div class="plannerDemo"><div class="plannerTop"><b>← Previous Week</b><strong>Weekly Planner</strong><b>Next Week →</b></div><div class="weekGrid">${['MON','TUE','WED','THU','FRI','SAT','SUN'].map((d,i)=>`<div><small>${d}</small>${i<3?'<button onclick="detail(\'Riverside Apartments · ABC Constructions · crew and vehicle allocation can be attached to the live project.\')"><b>Riverside Apartments</b><span>ABC Constructions</span><em>Active</em></button>':'<p>Available</p>'}</div>`).join('')}</div><div class="storyNote">Desktop planning can support drag-and-drop. Mobile planning uses clear date controls so the same weekly plan remains usable on site or away from the office.</div></div>`,
 'Staff & Employees':cards([['👥','Staff register','Employment details, attendance, agreed pay rates, qualifications and staff compliance records.'],['✓','Attendance','Record who is in and connect attendance to operational and pay information.'],['£','Pay information','Keep agreed day or hourly rates with the staff record.']]),
 'Staff Manager':`<div class="roleDemo"><div class="roleHero"><small>RESTRICTED MANAGEMENT WORKSPACE</small><h2>Staff Manager</h2><p>A dedicated workspace for the person responsible for workforce administration — without opening the whole company system.</p></div>${cards([['👥','Staff Records','Open and maintain workforce records.'],['✓','Attendance','See and manage attendance information.'],['🎓','Qualifications','Track competence and qualification information.'],['£','Pay Details','Work with authorised staff pay information.']])}</div>`,
 'Customers':cards([['🏢','Customer register','Contacts, addresses and customer account information.'],['📁','Project history','See current and completed work connected to the customer.'],['£','Account position','Connect customer activity to invoices, payments and outstanding values.']]),
 'Major Accounts':`<div class="majorDemo"><div class="majorStats"><div><small>PRIORITY CONTACTS</small><b>15</b></div><div><small>ORGANISATIONS</small><b>2</b></div><div><small>INTRODUCTIONS</small><b>Tracked</b></div><div><small>CONVERSION</small><b>Prospect → Customer</b></div></div><div class="majorTable"><h3>Strategic prospect register</h3><p><b>Matt Ellis</b><span>EQUANS · Divisional Manager</span><em>Introduction available</em></p><p><b>Claire Walmer-Smith</b><span>United Infrastructure · Senior Pre-Construction Manager</span><em>Tracked separately</em></p><button onclick="detail('Major Accounts can send separate personalised company introductions, retain send history and convert a successful prospect into the Customer register.')">See Major Accounts workflow →</button></div></div>`,
 'Purchasing Ledger':`<div class="purchaseDemo"><div class="opsKpis"><div><small>SUPPLIERS</small><b>Live</b><span>Account details</span></div><div><small>PURCHASE INVOICES</small><b>Tracked</b><span>Paid / unpaid / overdue</span></div><div><small>GOODS RECEIVED</small><b>Connected</b><span>Stock receipt control</span></div><div><small>LIABILITIES</small><b>Visible</b><span>Office & management</span></div></div>${cards([['🧾','Purchase Invoice','Record supplier, invoice number, dates, quantity, net, VAT and gross.'],['📦','Goods Received','Confirm physical receipt before linked scaffold material increases stock.'],['🏭','Supplier Account','Keep supplier contact details, account number, terms and notes.']])}</div>`,
 'Scaffold Stock':`<div class="stockDemo"><div class="stockHead"><div><small>OWNED STOCK</small><b>Recorded</b></div><div><small>ESTIMATED ON SITE</small><b>Project-linked</b></div><div><small>ESTIMATED AVAILABLE</small><b>Calculated</b></div></div><div class="dataRows"><p><b>Scaffold Boards</b><span>Owned · On Site · Available</span></p><p><b>Scaffold Tubes</b><span>Owned · On Site · Available</span></p><p><b>Fittings / Couplers</b><span>Owned · On Site · Available</span></p><p><b>Ladders / Brick Guards</b><span>Owned · On Site · Available</span></p></div><div class="storyNote">Live projects with sufficient measurements can contribute an approximate material allocation. Goods received through Purchasing can increase owned stock without pretending the estimate is a physical stocktake.</div></div>`,
 'Fleet & Vehicles':cards([['🚚','Vehicle Register','Registration, make/model, MOT, tax, insurance, service and operational status.'],['⚠','Renewals','Surface approaching vehicle dates and actions.'],['📍','Assignments','Connect vehicles to operational work where required.']]),
 'Plant & Equipment':cards([['🏗','Plant Register','Plant, tools and equipment remain visible even before every record is complete.'],['🔧','Maintenance','Inspection and maintenance information stays with the asset.'],['📋','Assignments','See availability and project allocation.']]),
 'Plant Manager':`<div class="roleDemo"><div class="roleHero"><small>RESTRICTED MANAGEMENT WORKSPACE</small><h2>Plant Manager</h2><p>A focused role for the person responsible for plant, equipment, inspection and maintenance records.</p></div>${cards([['🏗','Plant & Equipment','Maintain the operational register.'],['🔧','Inspections','See inspection and maintenance requirements.'],['📦','Availability','Understand what is available or allocated.']])}</div>`,
 'Accounts & Finance':cards([['🧾','Invoices','Invoice-ready work, issued invoices and status.'],['£','Outstanding Money','See money owed and support credit control.'],['✓','Payments','Record payments against the company financial position.']]),
 'Compliance & Safety':`<div class="complianceBoard"><div class="complianceScore"><small>OPERATIONAL COMPLIANCE</small><b>LIVE</b><span>Connected safety records</span></div><div class="checks"><button onclick="detail('Scaffold inspections and handover records stay connected to projects.')"><span class="good">PROJECTS</span><b>Scaffold inspections</b><small>Inspection / handover records</small></button><button onclick="detail('Workforce competence and qualification records can be surfaced before they become problems.')"><span class="good">STAFF</span><b>Competence</b><small>Qualifications & records</small></button><button onclick="detail('Plant, PPE and equipment records can retain inspection and maintenance information.')"><span class="good">ASSETS</span><b>Plant & PPE</b><small>Inspection awareness</small></button></div></div>`,
 'Office Staff Member':`<div class="roleDemo"><div class="roleHero"><small>RESTRICTED OFFICE WORKSPACE</small><h2>Office Staff Member</h2><p>Everyday administration without automatically exposing management, sensitive finance or system controls.</p></div>${cards([['🏢','Customers','Routine customer administration.'],['📁','Projects','Work with permitted project information.'],['📄','Documents','Create and manage authorised documents.'],['✉','Messages','Support day-to-day communication.']])}</div>`,
 'Remote Sales':`<div class="roleDemo"><div class="roleHero"><small>RESTRICTED SALES WORKSPACE</small><h2>Remote Sales</h2><p>Prospecting and follow-up tools without access to unrelated company operations.</p></div>${cards([['☎','Prospects','Capture potential customers and contacts.'],['✉','Introductions','Send company introductions.'],['↻','Follow-up','Keep next actions visible.']])}</div>`,
 'AI Briefing':`<div class="briefing"><div class="aiOrb">AI</div><div class="briefText"><small>JONCOR OPERATIONAL BRIEFING · DEMO</small><h2>Ask about the operation in normal language.</h2><p><b>Projects:</b> “Which active projects are missing measurements?”</p><p><b>Staff:</b> “Who is recorded in today?”</p><p><b>Purchasing:</b> “Open the purchasing ledger.”</p><p><b>Planning:</b> “Take me to the weekly planner.”</p><p><b>Major Accounts:</b> “Open Major Accounts.”</p><div class="voiceDemo"><button class="speakBtn" onclick="speakBriefing()">▶ Hear a demo briefing</button><span id="voiceStatus">Demo voice · uses your browser's speech engine</span></div><div class="whyPanel"><small>THE IDEA</small><h3>Business facts come from the connected records.</h3><p>Briefing is designed to make operational information easier to interrogate and navigate without turning business figures into guesswork.</p></div></div></div>`,
 'Subscription Details':`<div class="subHero"><div><small>JONCOR AI</small><h2>A connected operational platform for construction businesses.</h2><p>The demonstration shows how projects, people, customers, purchasing, stock, planning, portals and operational intelligence can work as one system.</p></div><div class="valueCard"><small>PLANNED SUBSCRIPTION</small><div class="subPrice"><strong>£149</strong><span>+ VAT / month</span></div><p>Register interest for launch information and availability.</p><button class="primary" onclick="subscription()">Register Subscription Interest</button></div></div>`
 };
 return content[active]||`<div class="whyPanel"><h3>${active}</h3><p>This area forms part of the connected JonCor operational demonstration.</p></div>`
}
function projectDemo(){
 const tabs=['Overview','Team','Documents','Inspections','Commercial'];
 const panels={
  Overview:`<div class="recordGrid"><div><small>SITE STATUS</small><b>Scaffold erected & live</b><p>Last site update: Today 14:20</p></div><div><small>WORKFORCE</small><b>3 operatives assigned</b><p>Staff Portal job is live</p></div><div><small>NEXT INSPECTION</small><b>Due tomorrow</b><p>Weekly inspection cycle</p></div><div><small>CLIENT ACCESS</small><b>Portal active</b><p>ABC Constructions</p></div></div><div class="timeline"><h3>Connected activity</h3><p><b>14:20</b> Site photo/update submitted from Staff Portal</p><p><b>13:05</b> Client message received: “Please confirm inspection record.”</p><p><b>08:10</b> Riverside assigned as today's live job</p></div>`,
  Team:`<div class="tabPanel"><h3>Assigned project team</h3><div class="dataRows"><p><b>Site Supervisor</b><span>Daniel Reed · On site</span></p><p><b>Scaffolder</b><span>Lewis Grant · On site</span></p><p><b>Scaffolder</b><span>Ryan Cole · On site</span></p></div><div class="storyNote">The assigned team sees Riverside Apartments as the live job in the Staff Portal, keeping the project record and workforce view connected.</div></div>`,
  Documents:`<div class="tabPanel"><h3>Project documents</h3><div class="dataRows"><p><b>RAMS / Method Statement</b><span>Current · client-facing</span></p><p><b>Handover record</b><span>Issued</span></p><p><b>Weekly inspection record</b><span>Next record due tomorrow</span></p></div><div class="storyNote">Relevant project documents stay attached to the job. Client-facing material can then be presented through the Client Portal without exposing internal records.</div></div>`,
  Inspections:`<div class="tabPanel"><h3>Scaffold inspection position</h3><div class="dataRows"><p><b>Last inspection</b><span>Passed · 7 days ago</span></p><p><b>Next inspection</b><span class="attention">Due tomorrow</span></p><p><b>Client visibility</b><span>Inspection record available</span></p></div><button class="actionBtn" onclick="openMod('Compliance')">Open Compliance workspace →</button></div>`,
  Commercial:`<div class="tabPanel"><h3>Commercial snapshot</h3><div class="dataRows"><p><b>Original quotation</b><span>£18,450.00</span></p><p><b>Approved variations</b><span>£1,275.00</span></p><p><b>Current project value</b><span>£19,725.00</span></p></div><button class="actionBtn" onclick="openMod('Commercial')">Open Commercial workspace →</button></div>`
 };
 return `<div class="record"><div class="recordHead"><div><small>PROJECT PRJ001 · ACTIVE</small><h2>Riverside Apartments</h2><p>Chelmsford, Essex · Client: ABC Constructions</p></div><span class="status">ON PROGRAMME</span></div><div class="recordTabs" role="tablist">${tabs.map(t=>`<button class="${projectTab===t?'selected':''}" onclick="setProjectTab('${t}')">${t}</button>`).join('')}</div>${panels[projectTab]}<div class="whyPanel"><small>WHY THIS MATTERS</small><h3>One project record connects the office, site team and client.</h3><p>Use the tabs above to see how workforce, documents, inspections and commercial information remain connected to the same live project instead of being scattered across separate systems.</p></div></div>`;
}
function phoneDemo(){return `<div class="portalStage"><div class="copy"><small>NOW LEAVE THE OFFICE</small><h2>Give the workforce the job information they need — on their phone.</h2><p>The Staff Portal turns the operative's phone into a controlled link between the site and the office. Assigned teams can see the live job, site address and relevant job information, then create the photographic and inspection record while the work is actually happening — without being given access to the main office system.</p><div class="featureList"><div><b>LIVE JOBS</b><span>See the assigned project, site address and relevant job information.</span></div><div><b>PHOTOGRAPHIC JOB RECORD</b><span>Capture progress, alterations and completed work from site. Photographs and notes create a clearer record for the office instead of being scattered across phones and messages.</span></div><div><b>SCAFFOLD INSPECTIONS & SCAFFTAG EVIDENCE</b><span>Record the inspection visit, notes, result, next due date and photographic evidence. Where the contractor provides ongoing inspection attendance after handover, each visit can remain visible against the project instead of relying on paper tags alone.</span></div><div><b>REAL-TIME CONNECTION</b><span>Site activity feeds back into the same operation used by the office, reducing double-entry and giving management a more current picture of the job.</span></div></div><div class="storyNote">The same <b>Riverside Apartments</b> project you saw in Management is now the operative's live job. A site update recorded here feeds back into the connected project information.</div></div><div class="bigphone interactivePhone"><div class="notch"></div><b>JONCOR STAFF</b><small>TODAY'S LIVE JOB</small><h3>Riverside Apartments</h3><p>Chelmsford, Essex</p><button class="mobileCard" onclick="detail('Site information: the assigned team can see Riverside Apartments, the site address and relevant project information without entering the main office workspace.')">Site information <b>OPEN</b></button><button class="mobileCard" onclick="detail('Scaffold inspection: the operational Staff Portal can record the competent inspector, result, notes, photographs and next inspection due date.')">Scaffold inspection <b>READY</b></button><button class="mobileCard" onclick="detail('Site update: operatives can record site notes and photographs. The operational portal supports events such as arrival, erection completion, alterations/additions and dismantle completion.')">Photo / site update <b>ADD</b></button><div class="phoneSync">● Connected back to the office project record</div></div></div>`}
function clientDemo(){return `<div class="clientStage"><div class="clientWindow"><header><b>CLIENT PORTAL</b><span>ABC Constructions</span></header><h2>Riverside Apartments</h2><div class="clientTiles"><button onclick="detail('My Projects: clients can see their linked projects, project status, address, scaffold stage, progress, dates and client-facing project information.')"><b>My Projects</b><small>Live project visibility</small></button><button onclick="detail('Inspection Records: recorded scaffold inspections linked to the client’s projects can be presented with inspection result, inspected date and next inspection due date.')"><b>Scaffold Inspections</b><small>Inspection / Scafftag visibility</small></button><button onclick="showSitePhotos()"><b>Site Photos & Updates</b><small>View photographic project record</small></button><button onclick="detail('Documents: the portal contains a client-facing document centre for relevant project material such as RAMS and method statements, handover/inspection records and approved commercial documents.')"><b>Documents</b><small>Controlled project information</small></button><button onclick="detail('Messages: the client can send a message directly to Office Operations. In the connected operation, that message can then become visible to the office and operational briefing.')"><b>Message Office</b><small>Direct client communication</small></button></div></div><div class="copy"><small>YOUR CUSTOMER'S VIEW</small><h2>Give the client answers without giving them your office system.</h2><p>The Client Portal is a built-in service window between contractor and customer. Each client gets controlled access to information linked to their own work: live projects, scaffold inspection records, site photographs and updates, relevant documents and direct messaging to Office Operations — without being given access to the contractor's internal system.</p><div class="featureList"><div><b>PROJECTS IN ONE CLIENT VIEW</b><span>Clients can see their own linked jobs, project status and progress in one place rather than chasing individual updates.</span></div><div><b>PHOTOS, INSPECTIONS & SCAFFTAG VISIBILITY</b><span>Site photographs and scaffold inspection information can give the client a clearer audit trail. Where weekly inspection attendance is being provided, the connected record helps the client see that visits are being recorded without repeatedly chasing the office.</span></div><div><b>FEWER ROUTINE CALLS</b><span>The customer can check routine information when it suits them, reducing avoidable calls and emails to the office.</span></div><div><b>CONTROLLED ACCESS</b><span>The customer sees client-facing information while internal operational records remain private.</span></div></div><div class="storyNote">A message sent here can flow back to <b>Office Operations</b> and be surfaced in the <b>AI Briefing</b> — showing why the portal is part of the connected operation, not a separate website.</div></div></div>`}
function guide(){const title=tourOrder[step];return `<div class="guide"><b>GUIDED TOUR ${step+1}/${tourOrder.length}</b><span>${title==='Staff Portal'?'Now see JonCor from the workforce perspective.':title==='Client Portal'?'Now see the same operation from your customer’s perspective.':title==='AI Briefing'?'JonCor does more than store information — see what needs attention.':'See how '+title+' fits into the connected operation.'}</span><button onclick="nextTour()">${step===tourOrder.length-1?'Finish tour':'Continue →'}</button><button class="skip" onclick="stopTour()">Explore freely</button></div>`}
window.enter=(guided)=>{screen='demo';tour=guided;step=0;active=guided?tourOrder[0]:'Management';render();scrollTo(0,0)};window.home=()=>{screen='landing';tour=false;render();scrollTo(0,0)};window.openMod=x=>{active=x;tour=false;render()};window.startTour=()=>{tour=true;step=0;active=tourOrder[0];render()};window.nextTour=()=>{if(step<tourOrder.length-1){step++;active=tourOrder[step];render()}else{tour=false;render();document.querySelector('.conversion')?.scrollIntoView({behavior:'smooth'})}};window.stopTour=()=>{tour=false;render()};window.detail=x=>{document.querySelector('#modal')?.remove();const m=document.createElement('div');m.id='modal';m.className='modal';m.innerHTML=`<div><small>INTERACTIVE DEMONSTRATION</small><h2>JonCor AI V4</h2><p>${x}</p><button class=primary onclick="this.closest('.modal').remove()">Continue exploring</button></div>`;document.body.appendChild(m)};window.subscription=()=>{document.querySelector('#subscriptionModal')?.remove();const m=document.createElement('div');m.id='subscriptionModal';m.className='modal subscriptionModal';m.innerHTML=`<div class="interestCard"><button class="close" onclick="this.closest('.modal').remove()">×</button><div class="interestBanner"><img src="assets/joncor-jc-logo.png" alt="JonCor JC logo"><div><b>JonCor AI <span>V4</span></b><small>OPERATIONAL INTELLIGENCE PLATFORM</small></div></div><div class="interestBody"><div class="interestTitle"><i>✉</i><div><h2>Register Your<br>Subscription Interest</h2></div></div><p>Be among the first to know when JonCor AI V4 subscriptions open. Register your interest for launch updates and availability.</p><form id="interestForm" onsubmit="sendInterest(event)"><div class="interestGrid"><label>Your Name *<input name="name" required placeholder="Enter your full name"></label><label>Your Email Address *<input name="email" type="email" required placeholder="Enter your email address"></label><label>Company Name *<input name="company" required placeholder="Enter your company name"></label><label>Your Role<select name="role"><option value="">Please select...</option><option>Owner / Managing Director</option><option>Director / Manager</option><option>Office Operations</option><option>Other</option></select></label><label>Phone Number<input name="phone" placeholder="Enter your phone number"></label><label>Additional Information<textarea name="info" placeholder="Any specific requirements or questions? (optional)"></textarea></label></div><div class="interestNotice">🔒 This simply registers your interest. It does not start a subscription and there is no payment required at this stage.</div><div class="interestActions"><button class="primary" type="submit">➤ Send My Subscription Interest</button><button class="ghost" type="button" onclick="this.closest('.modal').remove()">× Cancel</button></div></form></div></div>`;document.body.appendChild(m)};
window.sendInterest=(e)=>{e.preventDefault();const f=new FormData(e.target);const subject='JonCor AI V4 Subscription Interest';const body=`Hello,\n\nI would like to register my interest in the JonCor AI V4 subscription.\n\nName: ${f.get('name')}\nCompany: ${f.get('company')}\nEmail: ${f.get('email')}\nPhone: ${f.get('phone')||''}\nRole: ${f.get('role')||''}\n\nAdditional information:\n${f.get('info')||''}\n\nI understand this registers my interest only and does not start a subscription or take payment.`;window.location.href=`mailto:johncorne12@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`};
window.showSitePhotos=()=>{document.querySelector('#modal')?.remove();const m=document.createElement('div');m.id='modal';m.className='modal photoModal';m.innerHTML=`<div><button class="close" onclick="this.closest('.modal').remove()">×</button><small>CLIENT PORTAL · SITE PHOTOS & UPDATES</small><h2>Riverside Apartments</h2><p>Client-facing photographs can give the customer a visual record of progress, inspection attendance and completed scaffold activity without having to telephone the office for routine updates.</p><div class="photoGrid"><figure><img src="assets/scaffold-site-1.jpg" alt="Demonstration scaffold site photograph"><figcaption><b>Scaffold progress</b><span>Site update · Riverside Apartments</span></figcaption></figure><figure><img src="assets/scaffold-site-2.jpg" alt="Demonstration scaffold project photograph"><figcaption><b>Project record</b><span>Photographic evidence attached to the live job</span></figcaption></figure></div><div class="photoAudit"><span>✓ Linked to PRJ001</span><span>✓ Visible to ABC Constructions</span><span>✓ Retained with project history</span></div><button class="primary" onclick="this.closest('.modal').remove()">Continue exploring</button></div>`;document.body.appendChild(m)};
window.speakBriefing=()=>{if(!('speechSynthesis' in window)){detail('Voice playback is not supported by this browser.');return} speechSynthesis.cancel();const u=new SpeechSynthesisUtterance('Good morning. Three matters need your attention. A M H zero one has a vehicle inspection approaching in five days. A B C Constructions has sent a Client Portal message about the Riverside inspection record and is awaiting an Office Operations response. Riverside Apartments has its weekly scaffold inspection due tomorrow.');u.rate=.95;u.pitch=1;u.onstart=()=>{const e=document.querySelector('#voiceStatus');if(e)e.textContent='Speaking today’s operational briefing…'};u.onend=()=>{const e=document.querySelector('#voiceStatus');if(e)e.textContent='Briefing complete · press again to replay'};speechSynthesis.speak(u)};
render();
